apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DATABASE_USER: cG9zdGdyZXM=  # Base64 encoded value of 'postgres'
  DATABASE_PASSWORD: cG9zdGdyZXM=  # Base64 encoded value of 'postgres'
  SECRET_KEY: c2VjcmV0X2tleV92YWx1ZQ==  # Base64 encoded value of 'secret_key_value'
